### ISSUE TITLE
Add standard logging

### ISSUE THREAD

**Issue by rekibnikufesin** [computablelabs/capi#18]
At some point, having some logs will be helpful. 
Currently, anything written to `STDOUT` is sent to Cloudwatch Logs.
Add a default logger that supports info, debug, warn, and error messages
Set log format to a known standard format
Get the client IP address & log out as well (vs. the load balancer IP address which will be the default)
Bonus points: JSON payload for future parsing & aggregating logs

**Comment by robrobbins** [comment]
#31
