### ISSUE TITLE
Signature Recycle Sybil Attack

### ISSUE THREAD

**Issue by rbharath** [computablelabs/capi#51]
In the current design, the message for the `/authorize` endpoint works as follows:

    /authorize POST -> {message_hash: ..., signature: ..., public_key: ...}

This opens up an attack vector where an attacker gets a hold of an old message `{message_hash: ..., signature: ..., public_key: ...}`. This attacker can then continue to use this attack to authorize itself to the datatrust as the original signer. 

Here are a couple ideas to close off the attack:

- Have a initial call to get a `uuid` before the POST. Perhaps you could add a new endpoint
   `/authorize/uuid GET -> message`
  Which the signer has to sign to generate
   `/authorize POST -> {message_hash: ..., signature: ..., public_key: ...}`
  Each `uuid` can only be used for one call to `/authorize`. The downside of this approach is it requires two calls to CAPI to authorize.
- Have a datastructure on CAPI that tracks all `message_hashs` received so far. This datastructure prevents a double use of a signature. The downside is that this creates extra storage requirements on capi.

**Comment by robrobbins** [comment]
1. we are not going to pay to store every attempted login ever.
2. sign to get a thing you have to sign for. no.

i think there's a bunch of assumptions in here about risk and how to go about minimizing it. i think a bunch of them are wrong.

i agree we can have a conversation about the surface attack area here, what the actual risks are and what possible real world solutions exist or need be rolled by us.

@rekibnikufesin

**Comment by rbharath** [comment]
The general issue here is that there isn't a time to live on signatures; a valid signature is valid forevermore, so if you get your hands on a signature once, you can always break the authorization scheme. 

One alternate fix to this might be to have a standard message format: "FFA Market Wed 01-01-2020 6:00" with a timestamp. Then you know that this message is only valid until the TTL (say 90 minutes) past the original signing point.
